name: Tests

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev libgirepository1.0-dev
      - uses: getsentry/action-setup-venv@v2.1.0
        with:
          python-version: '3.12'
          install-cmd: pip install -r requirements.txt
      - run: python -m unittest
